include:
  - project: 'dolmen-tech/core/gitlabci'  
    ref: feature/java-ci-optim
    file: /components/slack.yml

stages:
  - notify

.alias:rules:release: &alias-rules-release
  if: '$CI_COMMIT_TAG =~ /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/'

.matcher:rules:release:
  rules:
    - <<: *alias-rules-release
      when: always

release:notify:
  stage: notify
  image: "debian:buster-slim"
  variables:
    WEBHOOK_URL: https://hooks.slack.com/services/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
    SLACK_COLOR: "#36a64f"
    SLACK_TITLE: "[KDT] Nouvelle version (${CI_COMMIT_TAG})"
    SLACK_TEXT: "Une nouvelle version de KDT est maintenant disponible.\ https://gitlab.com/dolmen-tech/tools/k8s-devops-toolkit/-/blob/${CI_COMMIT_TAG}/CHANGELOG.md"
  extends:
    - .slack:notif:send
  script:
    - echo "Ready"