version: "3.7"
services:
  kdt-machine:
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - kube:/home/devops/.kube
      - gcloud:/home/devops/.gcloud
    networks:
      - overlay
    
volumes:
  kube:
  gcloud:
networks:
  overlay: